# Generated by Django 6.0.5 on 2026-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frejolito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='persona',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
