# Generated by Django 6.0.5 on 2026-05-12 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frejolito', '0002_remove_persona_fecha_nacimiento_persona_es_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(default='General', max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('nivel_acceso', models.IntegerField(default=1)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='frejolito.persona')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('modulo_sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('puede_leer', models.BooleanField(default=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='panel.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('permisos_asignados', models.ManyToManyField(blank=True, related_name='roles_asociados', to='panel.permiso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='frejolito.persona')),
            ],
            options={
                'unique_together': {('nombre', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='DetalleRol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_dados', to='frejolito.persona')),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_rol', to='panel.rol')),
            ],
        ),
    ]
